service: crypto-dicebot

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    VERIFICATION_TOKEN: ${env:VERIFICATION_TOKEN}
functions:
  roll:
    handler: handler.roll
    events:
      - http:
          path: /roll
          method: post
          private: false
          cors: true
